name = "The Boys Modded Server"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "643b5bda658fc33746b7c0815c7f0e53b7f7732607d4658934c8f7ebdf391442"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
