name = "The Boys Modded Server"
author = "ImDefiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a728ae48f101a13d3ac82dc7c20a07c97af8c5366963e89001c012dd6f8f8b52"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
